"""Build composed models from hand-written parts with MjSpec.

INPUT   models/arm7.xml, models/gripper.xml (hand-written sources)
PROCESS MjSpec.attach composes them, MjSpec.to_xml serializes the result
OUTPUT  models/arm7_gripper.xml and models/bimanual.xml (generated, committed)

The generated files are checked in so the browser runtime, which loads plain
MJCF, sees exactly what Python sees. `tests/test_models.py` fails if a generated
file is stale, so edit the sources and rerun:

    python -m mjcourse.model_builder
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

import mujoco

from mjcourse.paths import MODELS_DIR

HEADER = (
    "<!--\n"
    "  GENERATED by mjcourse/model_builder.py from {sources}. Do not edit by hand:\n"
    "  edit the sources and run `python -m mjcourse.model_builder`.\n"
    "{notes}"
    "-->\n"
)


def _with_header(xml: str, sources: str, notes: str) -> str:
    # to_xml() records the keyframe count in <size nkey=.../>. That element makes
    # MJCF attachment report a size conflict in every scene that attaches the
    # generated file, and the compiler recounts keyframes anyway, so drop it.
    xml = re.sub(r"\n\s*<size nkey=\"\d+\"/>\n", "\n", xml)
    return HEADER.format(sources=sources, notes=notes) + xml


def build_arm7_gripper() -> mujoco.MjSpec:
    """Mount the parallel gripper on arm7's `flange` site.

    `attach(..., site=...)` places the child's world body in a new frame at the
    site, so the gripper inherits the flange pose. Names gain the "gripper/"
    prefix, which keeps them unique if a scene later attaches two arms.
    """
    arm = mujoco.MjSpec.from_file(str(MODELS_DIR / "arm7.xml"))
    gripper = mujoco.MjSpec.from_file(str(MODELS_DIR / "gripper.xml"))
    arm.modelname = "arm7_gripper"
    arm.attach(gripper, site="flange", prefix="gripper/")
    # The arm's own `ee` site sits where the gripper's tcp is; keep both so code
    # written for the bare arm runs unchanged on the gripper model.
    # The arm's keyframes list 7 joint values; extend them with an open gripper.
    for key in arm.keys:
        key.qpos = list(key.qpos)[:7] + [0.04, 0.04]
        key.ctrl = [0.0] * 7 + [0.04]
    arm.compile()  # validates the composition before we serialize it
    return arm


def build_arm7_peg() -> mujoco.MjSpec:
    """arm7 holding a cylindrical peg rigidly at the flange, for insertion tasks.

    The peg is welded to the flange (no joint): this removes grasp slip from the
    problem, so the insertion lessons study contact and compliance control only.
    Peg: radius 12 mm, length 100 mm, tip site `tool/peg_tip` at the free end.
    The tool is attached with prefix "tool/": an empty prefix would leave the
    tool's default class without a name, which MJCF cannot serialize.
    """
    arm = mujoco.MjSpec.from_file(str(MODELS_DIR / "arm7.xml"))
    arm.modelname = "arm7_peg"
    tool = mujoco.MjSpec()
    tool.compiler.degree = False
    peg = tool.worldbody.add_body(name="peg")
    peg.add_geom(name="peg_collar", type=mujoco.mjtGeom.mjGEOM_CYLINDER, size=[0.025, 0.01],
                 pos=[0, 0, 0.01], mass=0.1, rgba=[0.25, 0.27, 0.3, 1])
    peg.add_geom(name="peg", type=mujoco.mjtGeom.mjGEOM_CYLINDER, size=[0.012, 0.05],
                 pos=[0, 0, 0.07], mass=0.1, rgba=[0.9, 0.55, 0.15, 1],
                 friction=[0.3, 0.005, 0.0001], condim=3)
    peg.add_site(name="peg_tip", pos=[0, 0, 0.12], size=[0.006, 0, 0])
    arm.attach(tool, site="flange", prefix="tool/")
    arm.compile()
    return arm


def build_bimanual() -> mujoco.MjSpec:
    """Two arm7_gripper copies facing each other across a shared table.

    The left arm sits at y = +0.62 and the right arm at y = -0.62, both yawed to
    face the table. The box is long along y so each gripper can take one end. Each is attached into a frame with a prefix, so every name
    is unique: left/j1 ... left/gripper/grip, right/j1 ...
    """
    scene = mujoco.MjSpec()
    scene.modelname = "bimanual"
    scene.compiler.degree = False
    scene.option.timestep = 0.002
    scene.option.integrator = mujoco.mjtIntegrator.mjINT_IMPLICITFAST
    scene.option.cone = mujoco.mjtCone.mjCONE_ELLIPTIC
    scene.option.impratio = 10

    world = scene.worldbody
    world.add_light(pos=[0, 0, 2.5], dir=[0, 0, -1])
    world.add_geom(name="floor", type=mujoco.mjtGeom.mjGEOM_PLANE, size=[1.5, 1.5, 0.05],
                   rgba=[0.86, 0.88, 0.86, 1])
    world.add_geom(name="table", type=mujoco.mjtGeom.mjGEOM_BOX, size=[0.2, 0.25, 0.06],
                   pos=[0.45, 0, 0.06], rgba=[0.55, 0.45, 0.35, 1])

    box = world.add_body(name="box", pos=[0.45, 0, 0.15])
    box.add_freejoint(name="box")
    box.add_geom(name="box", type=mujoco.mjtGeom.mjGEOM_BOX, size=[0.025, 0.16, 0.03],
                 mass=0.4, rgba=[0.15, 0.45, 0.8, 1])

    for side, y, yaw in (("left", 0.62, -1.5707963), ("right", -0.62, 1.5707963)):
        arm = build_arm7_gripper()
        for key in list(arm.keys):  # per-arm keyframes would be padded and misleading
            arm.delete(key)
        quat = [float(v) for v in _yaw_quat(yaw)]
        frame = world.add_frame(name=f"{side}_mount", pos=[0.45, y, 0.0], quat=quat)
        frame.attach_body(arm.body("link0"), f"{side}/", "")

    scene.add_key(name="home", qpos=_bimanual_home())
    scene.compile()
    return scene


def _yaw_quat(yaw: float):
    import math

    return (math.cos(yaw / 2), 0.0, 0.0, math.sin(yaw / 2))


def _bimanual_home() -> list[float]:
    arm_home = [0, 0.2, 0, 1.9, 0, 1.0416, 0, 0.04, 0.04]
    box_free = [0.45, 0, 0.15, 1, 0, 0, 0]
    # qpos follows body order in the tree: the box was added first.
    return box_free + arm_home + arm_home


def write_all(out_dir: Path = MODELS_DIR) -> dict[str, str]:
    """Build every composed model and return {filename: xml}; write them to out_dir."""
    outputs = {
        "arm7_gripper.xml": _with_header(
            build_arm7_gripper().to_xml(), "arm7.xml + gripper.xml",
            "  ctrl layout (8): a1..a7 joint torques (N m), then gripper/grip half-opening (m).\n"),
        "arm7_peg.xml": _with_header(
            build_arm7_peg().to_xml(), "arm7.xml + a peg tool built in model_builder.py",
            "  ctrl layout (7): a1..a7 joint torques (N m). The peg is rigidly fixed to the flange.\n"),
        "bimanual.xml": _with_header(
            build_bimanual().to_xml(), "arm7.xml + gripper.xml (twice)",
            "  ctrl layout (16): left/a1..a7, left/gripper/grip, right/a1..a7, right/gripper/grip.\n"),
    }
    for name, xml in outputs.items():
        (out_dir / name).write_text(xml)
    return outputs


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", type=Path, default=MODELS_DIR)
    args = parser.parse_args()
    for name in write_all(args.out):
        print(f"wrote {args.out / name}")


if __name__ == "__main__":
    main()
