#!/usr/bin/env python3
"""Convert site images to WebP at display-appropriate sizes and rewrite references.

Every figure on the site renders at 372px wide or less, so shipping 1-4 MB source
PNGs was sending ~10-30x more pixels than any visitor sees. For each source image
this writes two derivatives and repoints the templates/data at them:

    images/<slug>.webp      max 960w  - the <img> src, and the lightbox target
    images/<slug>-sm.webp   max 480w  - small figures (publication cards, avatars)

Templates pair them with srcset so the browser picks per viewport and DPR.

Usage:
    python3 scripts/optimize_images.py --dry-run   # report what would change
    python3 scripts/optimize_images.py             # convert + rewrite + delete originals
"""
from __future__ import annotations

import argparse
import glob
import os
import re
import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow is required: pip install --user Pillow")

ROOT = Path(__file__).resolve().parent.parent
IMAGES = ROOT / "images"

WIDE, SMALL = 960, 480
Q_WIDE, Q_SMALL = 80, 78

# Files that are icons/manifest assets or already tiny: never touch.
SKIP = {
    "safari-pinned-tab.svg", "manifest.json", "browserconfig.xml",
    "mstile-144x144.png", "500x300.png", "bio-photo.jpg", "bio-photo-2.jpg",
}

# Source files whose names carry spaces/parentheses (which become %20 in URLs) get
# an explicit slug; everything else is slugified from its stem.
RENAME = {
    "Computer Device for Coding and Algorithm Simulation(UK_Patent).jpg":
        "uk-patent-coding-algorithm-simulation",
    "Screenshot 2026-02-27 083432.jpg": "screenshot-2026-02-27",
    "2026_Proposal - Copy.gif": "2026-proposal",
    "Parkinsos_gait_framework.jpg": "parkinsons-gait-framework",  # source misspells "Parkinsons"
}

SEARCH_GLOBS = ["_data/*.yml", "_pages/*", "_includes/*", "_layouts/*", "_config.yml"]


def slugify(stem: str) -> str:
    s = re.sub(r"[^a-zA-Z0-9]+", "-", stem).strip("-").lower()
    return re.sub(r"-{2,}", "-", s)


def referenced_files() -> tuple[set[str], str]:
    blob = ""
    for pat in SEARCH_GLOBS:
        for f in glob.glob(str(ROOT / pat)):
            if os.path.isfile(f):
                blob += Path(f).read_text(encoding="utf-8", errors="replace")
    names = {p.name for p in IMAGES.iterdir()
             if p.is_file() and (p.name in blob or p.name.replace(" ", "%20") in blob)}
    return names, blob


def encode(src: Path, dst: Path, max_w: int, quality: int) -> int:
    with Image.open(src) as im:
        if im.mode in ("P", "LA"):
            im = im.convert("RGBA")
        elif im.mode == "CMYK":
            im = im.convert("RGB")
        if im.width > max_w:
            h = round(im.height * max_w / im.width)
            im = im.resize((max_w, h), Image.LANCZOS)
        # Flatten transparency onto white: these are figures on light cards, and
        # keeping alpha roughly doubles the file for no visible gain.
        if im.mode == "RGBA":
            bg = Image.new("RGB", im.size, (255, 255, 255))
            bg.paste(im, mask=im.split()[-1])
            im = bg
        im.convert("RGB").save(dst, "WEBP", quality=quality, method=6)
    return dst.stat().st_size


def write_manifest() -> int:
    """Emit _data/image_sizes.yml so templates can set width/height on every <img>.

    Intrinsic dimensions on the tag reserve the right box before the bytes land,
    which is what stops figures shoving the page around as they decode.
    """
    rows = []
    for p in sorted(IMAGES.glob("*.webp")):
        if p.stem.endswith("-sm"):
            continue
        with Image.open(p) as im:
            has_sm = (p.parent / f"{p.stem}-sm.webp").exists()
            rows.append((p.stem, im.width, im.height, str(has_sm).lower()))
    out = ROOT / "_data" / "image_sizes.yml"
    lines = [
        "# Intrinsic size of each display-size image, used to set width/height on <img>",
        "# so figures cannot shift the layout while they load.",
        "# Generated by scripts/optimize_images.py - do not hand-edit.",
        "",
    ]
    lines += ['%s: { w: %d, h: %d, sm: %s }' % r for r in rows]
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote %s (%d images)" % (out.relative_to(ROOT), len(rows)))
    return len(rows)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--manifest-only", action="store_true",
                    help="regenerate _data/image_sizes.yml without re-encoding")
    args = ap.parse_args()

    if args.manifest_only:
        write_manifest()
        return

    names, _ = referenced_files()
    targets = sorted(n for n in names if n not in SKIP
                     and Path(n).suffix.lower() in {".png", ".jpg", ".jpeg", ".gif", ".webp"})
    if not targets:
        sys.exit("No referenced raster images found.")

    mapping, before, after = {}, 0, 0
    for name in targets:
        src = IMAGES / name
        slug = RENAME.get(name) or slugify(Path(name).stem)
        wide, small = IMAGES / f"{slug}.webp", IMAGES / f"{slug}-sm.webp"
        orig = src.stat().st_size
        before += orig

        if args.dry_run:
            with Image.open(src) as im:
                print(f"  {name:<52} {orig/1024:>7.0f} KB  {im.width}x{im.height}"
                      f"  ->  {wide.name}, {small.name}")
            continue

        # Encode to temp names first so a source/target collision (x.webp -> x.webp)
        # cannot truncate the source before it has been read.
        tmp_w, tmp_s = wide.with_suffix(".tmp.webp"), small.with_suffix(".tmp.webp")
        nw = encode(src, tmp_w, WIDE, Q_WIDE)
        ns = encode(src, tmp_s, SMALL, Q_SMALL)
        if src != wide and src != small:
            src.unlink()
        tmp_w.replace(wide)
        tmp_s.replace(small)
        after += nw + ns
        mapping[name] = slug
        print(f"  {name:<52} {orig/1024:>7.0f} KB -> {nw/1024:>6.0f} + {ns/1024:>5.0f} KB")

    if args.dry_run:
        print(f"\n{len(targets)} images, {before/1024/1024:.1f} MB (dry run)")
        return

    # Rewrite every reference: bare name, URL-encoded name, and bare stem.
    changed = []
    for pat in SEARCH_GLOBS:
        for f in glob.glob(str(ROOT / pat)):
            if not os.path.isfile(f):
                continue
            p = Path(f)
            txt = orig_txt = p.read_text(encoding="utf-8", errors="replace")
            for name, slug in mapping.items():
                txt = txt.replace(name, f"{slug}.webp")
                txt = txt.replace(name.replace(" ", "%20"), f"{slug}.webp")
            if txt != orig_txt:
                p.write_text(txt, encoding="utf-8")
                changed.append(p.relative_to(ROOT).as_posix())

    print(f"\n{len(mapping)} images: {before/1024/1024:.2f} MB -> {after/1024/1024:.2f} MB "
          f"({100 - after * 100 / before:.0f}% smaller)")
    print("rewrote references in:", ", ".join(sorted(changed)) or "nothing")
    write_manifest()


if __name__ == "__main__":
    main()
